//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDRownakJahanTanjil_296627.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ReqID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string MessageTitle { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
    }
}
